web:
  container_name: phpmyadmin
  image: phpmyadmin/phpmyadmin
  ports:
    - "8081:80"
  external_links:
    - main-mysql:db
#  environment:
#    PMA_ARBITRARY:		# when set to 1 connection to the arbitrary server will be allowed
#    PMA_HOST: 			# define address/host name of the MySQL server
#    PMA_PORT:			# define port of the MySQL server
#    PMA_HOSTS: 		# define comma separated list of address/host names of the MySQL servers
#    PMA_USER and PMA_PASSWORD:	# define username to use for config authentication method
#    PHP_UPLOAD_MAX_FILESIZE: 	# define upload_max_filesize and post_max_size PHP settings
#    PHP_MAX_INPUT_VARS:	# define max_input_vars PHP setting
